// Application route path constants

export const ROUTES = {
  HOME: '/',
  ABOUT: '/about',
  COURSES: '/courses',
  COURSE_DETAIL: '/course/:courseId',
  CART: '/cart',
  CONTACT: '/contact',
  TESTIMONIAL: '/testimonial',
  TEAM: '/team',
  INSTRUCTOR: '/instructor',
  MENTOR_PROFILE: '/mentor/:id',
  FAQ: '/faq',
  BLOG: '/blog',
  BLOG_DETAIL: '/blog/:id',
  LOGIN: '/login',
  SIGNUP: '/signup',
  FORGOT_PASSWORD: '/forgot-password',
  INSTRUCTOR_DASHBOARD: '/instructor-dashboard',
  STUDENT_DASHBOARD: '/student-dashboard',
  CREATE_COURSE: '/create-course',
  ROADMAP: '/roadmap',
  ROADMAP_DETAIL: '/roadmap/:category',
  MEETING: '/meeting',
  MEETING_ROOM: '/meeting/:roomId',
  MENTEE_FORM: '/mentee-form',
  MENTEE_LIST: '/mentee-list',
  PORTFOLIO: '/portfolio',
  HOMEWORK: '/homework',
  COMPETENCY_PROFILE: '/competency-profile',
  ASSIGNMENT_SUBMISSION: '/assignment-submission',
  SETTINGS: '/settings',
  NOTIFICATIONS: '/notifications',
  SEARCH: '/search',
  PROFILE: '/profile',
  CERTIFICATES: '/certificates',
  HELP: '/help',
  CHANGELOG: '/changelog',
  BOOKMARKS: '/bookmarks',
  ANALYTICS: '/analytics',
  COMMUNITY: '/community',
  EVENTS: '/events',
  RESOURCES: '/resources',
  PRIVACY_POLICY: '/privacy-policy',
  TERMS_OF_SERVICE: '/terms-of-service',
  NOT_FOUND: '*',
} as const;

export type RoutePath = (typeof ROUTES)[keyof typeof ROUTES];
